In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [2]:
import pandas as pd

train = pd.read_csv('train_df_errno.csv')
test = pd.read_csv('test_df.csv')
sub = pd.read_csv('sample_submission.csv')
age = pd.read_csv('age_gender_info.csv')

train.shape, test.shape, sub.shape, age.shape

((2896, 15), (1008, 14), (150, 2), (16, 23))

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2896 entries, 0 to 2895
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   단지코드        2896 non-null   object
 1   총세대수        2896 non-null   int64
 2   임대건물구분      2896 non-null   object
 3   지역          2896 non-null   object
 4   공급유형        2896 non-null   object
 5   전용면적        2896 non-null   float64
 6   전용면적별세대수    2896 non-null   int64
 7   공가수         2896 non-null   float64
 8   자격유형        2896 non-null   object
 9   임대보증금       2327 non-null   object
 10  임대료         2327 non-null   object
 11  10분내지하철수    2685 non-null   float64
 12  10분내버스정류장수  2892 non-null   float64
 13  단지내주차면수     2896 non-null   float64
 14  등록차량수       2896 non-null   float64
dtypes: float64(6), int64(2), object(7)
memory usage: 339.5+ KB

In [4]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   단지코드        1008 non-null   object
 1   총세대수        1008 non-null   int64
 2   임대건물구분      1008 non-null   object
 3   지역          1008 non-null   object
 4   공급유형        1008 non-null   object
 5   전용면적        1008 non-null   float64
 6   전용면적별세대수    1008 non-null   int64
 7   공가수         1008 non-null   float64
 8   자격유형        1006 non-null   object
 9   임대보증금       828 non-null    object
 10  임대료         828 non-null    object
 11  10분내지하철수    970 non-null    float64
 12  10분내버스정류장수  1008 non-null   float64
 13  단지내주차면수     1008 non-null   float64
dtypes: float64(5), int64(2), object(7)
memory usage: 110.4+ KB

In [5]:
train.isna().sum()

단지코드            0
총세대수            0
임대건물구분          0
지역              0
공급유형            0
전용면적            0
전용면적별세대수        0
공가수             0
자격유형            0
임대보증금         569
임대료           569
10분내지하철수      211
10분내버스정류장수      4
단지내주차면수         0
등록차량수           0
dtype: int64

In [6]:
test.isna().sum()

단지코드            0
총세대수            0
임대건물구분          0
지역              0
공급유형            0
전용면적            0
전용면적별세대수        0
공가수             0
자격유형            2
임대보증금         180
임대료           180
10분내지하철수       38
10분내버스정류장수      0
단지내주차면수         0
dtype: int64

In [7]:
sel = ['총세대수']
X_train = train[sel]
X_test = test[sel]

y_train = train['등록차량수']

In [8]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)
pred = model.predict(X_test)
pred

array([519.66988273, 519.66988273, 519.66988273, ..., 414.75241208,
       414.75241208, 414.75241208])

In [9]:
len(pred)

1008

In [10]:
len(sub)

150

In [11]:
len(test['단지코드'].unique())

147

In [12]:
import numpy as np

In [13]:
test['등록차량수'] = pred
test['코드별차량수평균'] = test.groupby('단지코드')['등록차량수'].transform(np.mean)
test.head(10)

,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,10분내지하철수,10분내버스정류장수,단지내주차면수,등록차량수,코드별차량수평균
0,C1072,754,아파트,경기도,국민임대,39.79,116,14.0,H,22830000,189840,0.0,2.0,683.0,519.669883,519.669883
1,C1072,754,아파트,경기도,국민임대,46.81,30,14.0,A,36048000,249930,0.0,2.0,683.0,519.669883,519.669883
2,C1072,754,아파트,경기도,국민임대,46.90,112,14.0,H,36048000,249930,0.0,2.0,683.0,519.669883,519.669883
3,C1072,754,아파트,경기도,국민임대,46.90,120,14.0,H,36048000,249930,0.0,2.0,683.0,519.669883,519.669883
4,C1072,754,아파트,경기도,국민임대,51.46,60,14.0,H,43497000,296780,0.0,2.0,683.0,519.669883,519.669883
5,C1072,754,아파트,경기도,국민임대,51.71,51,14.0,H,43497000,296780,0.0,2.0,683.0,519.669883,519.669883
6,C1072,754,아파트,경기도,국민임대,51.96,198,14.0,H,43497000,296780,0.0,2.0,683.0,519.669883,519.669883
7,C1072,754,아파트,경기도,국민임대,51.96,67,14.0,H,43497000,296780,0.0,2.0,683.0,519.669883,519.669883
8,C1128,1354,아파트,경기도,국민임대,39.79,368,9.0,H,22830000,189840,0.0,3.0,1216.0,688.891610,688.891610
9,C1128,1354,아파트,경기도,국민임대,39.79,30,9.0,H,22830000,189840,0.0,3.0,1216.0,688.891610,688.891610

In [14]:
# 중복 제거
test_new = test.drop_duplicates(['단지코드'], keep='first').reset_index()  # 중복 제외
test_new

,index,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,10분내지하철수,10분내버스정류장수,단지내주차면수,등록차량수,코드별차량수평균
0,0,C1072,754,아파트,경기도,국민임대,39.79,116,14.0,H,22830000,189840,0.0,2.0,683.0,519.669883,519.669883
1,8,C1128,1354,아파트,경기도,국민임대,39.79,368,9.0,H,22830000,189840,0.0,3.0,1216.0,688.891610,688.891610
2,17,C1456,619,아파트,부산광역시,국민임대,33.40,82,18.0,A,19706000,156200,0.0,16.0,547.0,481.594994,481.594994
3,26,C1840,593,아파트,전라북도,국민임대,39.57,253,7.0,A,14418000,108130,0.0,3.0,543.0,474.262053,474.262053
4,30,C1332,1297,아파트,경기도,국민임대,39.99,282,11.0,H,28598000,203050,0.0,2.0,1112.0,672.815546,672.815546
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,982,C2456,349,아파트,제주특별자치도,국민임대,26.44,24,17.0,H,6992000,117000,0.0,4.0,270.0,405.445217,405.445217
143,986,C1266,596,아파트,충청북도,국민임대,26.94,164,35.0,H,8084000,149910,0.0,1.0,593.0,475.108161,475.108161
144,991,C2152,120,아파트,강원도,영구임대,24.83,66,9.0,C,-,-,0.0,1.0,40.0,340.858925,340.858925
145,993,C1267,675,아파트,경상남도,국민임대,24.87,28,38.0,H,6882000,104370,0.0,1.0,467.0,497.389022,497.389022
146,1004,C2189,382,아파트,전라북도,국민임대,29.19,96,45.0,H,6872000,106400,0.0,2.0,300.0,414.752412,414.752412

In [15]:
sub_df = test_new[['단지코드','코드별차량수평균']]
sub_df.columns = ['code', 'num']
sub_df.to_csv('baseline_0712.csv', index=False)
sub_df.head()

    code         num
0  C1072  519.669883
1  C1128  688.891610
2  C1456  481.594994
3  C1840  474.262053
4  C1332  672.815546

In [16]:
import os
os.listdir(os.getcwd())

['.git',
 '.ipynb_checkpoints',
 '00_data_visualization_matplotlib.ipynb',
 '01_데이터셋_살펴보기.ipynb',
 '02_second_model.ipynb',
 '03_third_model.ipynb',
 '04_fourth_model.ipynb',
 '05_fifth_parking_demand.ipynb',
 '20210716_dacon_review.ipynb',
 'age_gender_info.csv',
 'baseline_0712.csv',
 'baseline_practice_0712.csv',
 'cache',
 'README.md',
 'sample_submission.csv',
 'second_practice_randomforest_20210712.csv',
 'test.csv',
 'test_df.csv',
 'third_practice_randomforest_20210712.csv',
 'third_rf_0714.csv',
 'train',
 'train.csv',
 'train_df_errno.csv',
 '[베이스라인]_데이콘 베이스라인 코드 - 랜덤포레스트.ipynb']

In [17]:
sub_df.shape

(147, 2)

In [18]:
add_dat = {'code':['C2675', 'C2335', 'C1327'],
          'num':['0','0','0']}
add_df = pd.DataFrame(add_dat)
add_df

    code num
0  C2675   0
1  C2335   0
2  C1327   0

In [19]:
sub_df = pd.concat([sub_df, add_df]).reset_index()
sub_df = sub_df.drop(['index'], axis=1)
sub_df.to_csv('third_rf_0714.csv', index=False)
sub_df

      code      num
0    C1072   519.67
1    C1128  688.892
2    C1456  481.595
3    C1840  474.262
4    C1332  672.816
..     ...      ...
145  C1267  497.389
146  C2189  414.752
147  C2675        0
148  C2335        0
149  C1327        0

[150 rows x 2 columns]

### 결측치 처리

In [20]:
train.isnull().sum()

단지코드            0
총세대수            0
임대건물구분          0
지역              0
공급유형            0
전용면적            0
전용면적별세대수        0
공가수             0
자격유형            0
임대보증금         569
임대료           569
10분내지하철수      211
10분내버스정류장수      4
단지내주차면수         0
등록차량수           0
dtype: int64

In [21]:
test.isnull().sum()

단지코드            0
총세대수            0
임대건물구분          0
지역              0
공급유형            0
전용면적            0
전용면적별세대수        0
공가수             0
자격유형            2
임대보증금         180
임대료           180
10분내지하철수       38
10분내버스정류장수      0
단지내주차면수         0
등록차량수           0
코드별차량수평균        0
dtype: int64

### 자격유형 결측치 처리

In [22]:
test.loc[test['자격유형'].isnull()]

,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,10분내지하철수,10분내버스정류장수,단지내주차면수,등록차량수,코드별차량수평균
196,C2411,962,아파트,경상남도,국민임대,46.90,240,25.0,NaN,71950000,37470,0.0,2.0,840.0,578.333415,578.333415
258,C2253,1161,아파트,강원도,영구임대,26.37,745,0.0,NaN,2249000,44770,0.0,2.0,173.0,634.458621,634.458621

In [23]:
grouped = test.groupby(['단지코드','임대건물구분','지역','공급유형'])
group1 = grouped.get_group(('C2411','아파트','경상남도','국민임대'))
group1

,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,10분내지하철수,10분내버스정류장수,단지내주차면수,등록차량수,코드별차량수평균
193,C2411,962,아파트,경상남도,국민임대,39.43,56,25.0,A,11992000,100720,0.0,2.0,840.0,578.333415,578.333415
194,C2411,962,아파트,경상남도,국민임대,39.72,336,25.0,A,11992000,100720,0.0,2.0,840.0,578.333415,578.333415
195,C2411,962,아파트,경상남도,국민임대,39.82,179,25.0,A,11992000,100720,0.0,2.0,840.0,578.333415,578.333415
196,C2411,962,아파트,경상남도,국민임대,46.90,240,25.0,NaN,71950000,37470,0.0,2.0,840.0,578.333415,578.333415
197,C2411,962,아파트,경상남도,국민임대,51.93,150,25.0,A,21586000,171480,0.0,2.0,840.0,578.333415,578.333415

In [24]:
test.loc[196, '자격유형']='A'

In [25]:
group2 = grouped.get_group( ('C2253', '아파트', '강원도', '영구임대')  )
group2

,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,10분내지하철수,10분내버스정류장수,단지내주차면수,등록차량수,코드별차량수평균
258,C2253,1161,아파트,강원도,영구임대,26.37,745,0.0,NaN,2249000,44770,0.0,2.0,173.0,634.458621,634.458621
259,C2253,1161,아파트,강원도,영구임대,31.32,239,0.0,C,3731000,83020,0.0,2.0,173.0,634.458621,634.458621
260,C2253,1161,아파트,강원도,영구임대,31.32,149,0.0,C,3731000,83020,0.0,2.0,173.0,634.458621,634.458621

In [26]:
test.loc[258, '자격유형']='C'

In [27]:
test.loc[[196,258], : ]

,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,10분내지하철수,10분내버스정류장수,단지내주차면수,등록차량수,코드별차량수평균
196,C2411,962,아파트,경상남도,국민임대,46.90,240,25.0,A,71950000,37470,0.0,2.0,840.0,578.333415,578.333415
258,C2253,1161,아파트,강원도,영구임대,26.37,745,0.0,C,2249000,44770,0.0,2.0,173.0,634.458621,634.458621

In [28]:
test.isnull().sum()

단지코드            0
총세대수            0
임대건물구분          0
지역              0
공급유형            0
전용면적            0
전용면적별세대수        0
공가수             0
자격유형            0
임대보증금         180
임대료           180
10분내지하철수       38
10분내버스정류장수      0
단지내주차면수         0
등록차량수           0
코드별차량수평균        0
dtype: int64

In [29]:
train.isnull().sum()

단지코드            0
총세대수            0
임대건물구분          0
지역              0
공급유형            0
전용면적            0
전용면적별세대수        0
공가수             0
자격유형            0
임대보증금         569
임대료           569
10분내지하철수      211
10분내버스정류장수      4
단지내주차면수         0
등록차량수           0
dtype: int64

In [30]:
train.loc[ train['10분내버스정류장수'].isnull(), :]

,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,10분내지하철수,10분내버스정류장수,단지내주차면수,등록차량수
2293,N2431,1047,아파트,경상남도,공공임대(10년),74.97,80,15.0,A,46000000,456000,NaN,NaN,1066.0,1214.0
2294,N2431,1047,아파트,경상남도,공공임대(10년),84.95,124,15.0,A,57000000,462000,NaN,NaN,1066.0,1214.0
2295,N2431,1047,아파트,경상남도,공공임대(10년),84.96,289,15.0,A,57000000,462000,NaN,NaN,1066.0,1214.0
2296,N2431,1047,아파트,경상남도,공공임대(10년),84.98,82,15.0,A,57000000,462000,NaN,NaN,1066.0,1214.0

In [31]:
grouped = train.groupby(['임대건물구분', '지역','공급유형', '자격유형'])
group1 = grouped.get_group(('아파트', '경상남도', '공공임대(10년)', 'A'))
group1

,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,10분내지하철수,10분내버스정류장수,단지내주차면수,등록차량수
2158,C1788,376,아파트,경상남도,공공임대(10년),51.59,116,28.0,A,29000000,340000,0.0,3.0,380.0,412.0
2159,C1788,376,아파트,경상남도,공공임대(10년),59.97,260,28.0,A,36000000,390000,0.0,3.0,380.0,412.0
2208,C2405,600,아파트,경상남도,공공임대(10년),75.84,48,22.0,A,36019000,603480,0.0,8.0,728.0,1240.0
2209,C2405,600,아파트,경상남도,공공임대(10년),75.99,54,22.0,A,36113000,603480,0.0,8.0,728.0,1240.0
2210,C2405,600,아파트,경상남도,공공임대(10년),84.95,182,22.0,A,44868000,636400,0.0,8.0,728.0,1240.0
2293,N2431,1047,아파트,경상남도,공공임대(10년),74.97,80,15.0,A,46000000,456000,NaN,NaN,1066.0,1214.0
2294,N2431,1047,아파트,경상남도,공공임대(10년),84.95,124,15.0,A,57000000,462000,NaN,NaN,1066.0,1214.0
2295,N2431,1047,아파트,경상남도,공공임대(10년),84.96,289,15.0,A,57000000,462000,NaN,NaN,1066.0,1214.0
2296,N2431,1047,아파트,경상남도,공공임대(10년),84.98,82,15.0,A,57000000,462000,NaN,NaN,1066.0,1214.0
2498,C1941,404,아파트,경상남도,공공임대(10년),84.94,64,19.0,A,47288000,627080,0.0,3.0,490.0,600.0
2499,C1941,404,아파트,경상남도,공공임대(10년),84.94,72,19.0,A,47288000,627080,0.0,3.0,490.0,600.0
2500,C1941,404,아파트,경상남도,공공임대(10년),84.96,16,19.0,A,47288000,627080,0.0,3.0,490.0,600.0
2501,C1941,404,아파트,경상남도,공공임대(10년),84.99,252,19.0,A,47288000,627080,0.0,3.0,490.0,600.0
2594,C1284,528,아파트,경상남도,공공임대(10년),59.72,59,0.0,A,32896000,185040,0.0,5.0,543.0,780.0
2595,C1284,528,아파트,경상남도,공공임대(10년),59.92,469,0.0,A,32896000,185040,0.0,5.0,543.0,780.0
2596,C2595,867,아파트,경상남도,공공임대(10년),59.95,137,2.0,A,38000000,430000,0.0,5.0,897.0,1359.0
2597,C2595,867,아파트,경상남도,공공임대(10년),59.96,557,2.0,A,38000000,430000,0.0,5.0,897.0,1359.0
2598,C2595,867,아파트,경상남도,공공임대(10년),74.93,105,2.0,A,44000000,550000,0.0,5.0,897.0,1359.0
2599,C2595,867,아파트,경상남도,공공임대(10년),84.90,60,2.0,A,54000000,620000,0.0,5.0,897.0,1359.0
2600,C2595,867,아파트,경상남도,공공임대(10년),84.98,8,2.0,A,54000000,620000,0.0,5.0,897.0,1359.0

In [32]:
group1['10분내버스정류장수'].mean()

4.8125

In [33]:
# 데이터 확인 후, 임의 처리 4
train.loc[train['10분내버스정류장수'].isnull(), "10분내버스정류장수"] = 5
train.loc[train['10분내버스정류장수'].isnull(), :]

Empty DataFrame
Columns: [단지코드, 총세대수, 임대건물구분, 지역, 공급유형, 전용면적, 전용면적별세대수, 공가수, 자격유형, 임대보증금, 임대료, 10분내지하철수, 10분내버스정류장수, 단지내주차면수, 등록차량수]
Index: []

In [34]:
train.isnull().sum()

단지코드            0
총세대수            0
임대건물구분          0
지역              0
공급유형            0
전용면적            0
전용면적별세대수        0
공가수             0
자격유형            0
임대보증금         569
임대료           569
10분내지하철수      211
10분내버스정류장수      0
단지내주차면수         0
등록차량수           0
dtype: int64

In [35]:
test.isnull().sum()

단지코드            0
총세대수            0
임대건물구분          0
지역              0
공급유형            0
전용면적            0
전용면적별세대수        0
공가수             0
자격유형            0
임대보증금         180
임대료           180
10분내지하철수       38
10분내버스정류장수      0
단지내주차면수         0
등록차량수           0
코드별차량수평균        0
dtype: int64

In [36]:
train.head()

,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,10분내지하철수,10분내버스정류장수,단지내주차면수,등록차량수
0,C2515,545,아파트,경상남도,국민임대,33.48,276,17.0,A,9216000,82940,0.0,3.0,624.0,205.0
1,C2515,545,아파트,경상남도,국민임대,39.60,60,17.0,A,12672000,107130,0.0,3.0,624.0,205.0
2,C2515,545,아파트,경상남도,국민임대,39.60,20,17.0,A,12672000,107130,0.0,3.0,624.0,205.0
3,C2515,545,아파트,경상남도,국민임대,46.90,38,17.0,A,18433000,149760,0.0,3.0,624.0,205.0
4,C2515,545,아파트,경상남도,국민임대,46.90,19,17.0,A,18433000,149760,0.0,3.0,624.0,205.0

In [37]:
print(train.자격유형.unique())
print(test.자격유형.unique())

mapping = {'A':1, 'B':2, 'C':3, 'D':4, 'E':5, 'F':6, 'G':7, 'H':8, 'I':9, 'J':10,
            'K':11, 'L':12, 'M':13, 'N':14, 'O':15}

train['자격유형'] =train['자격유형'].map(mapping).astype(int)
test['자격유형'] =test['자격유형'].map(mapping).astype(int)

train.head(3)

['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O']
['H' 'A' 'E' 'C' 'D' 'G' 'I' 'J' 'K' 'L' 'M' 'N']

,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,10분내지하철수,10분내버스정류장수,단지내주차면수,등록차량수
0,C2515,545,아파트,경상남도,국민임대,33.48,276,17.0,1,9216000,82940,0.0,3.0,624.0,205.0
1,C2515,545,아파트,경상남도,국민임대,39.60,60,17.0,1,12672000,107130,0.0,3.0,624.0,205.0
2,C2515,545,아파트,경상남도,국민임대,39.60,20,17.0,1,12672000,107130,0.0,3.0,624.0,205.0

In [38]:
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.model_selection import train_test_split

In [39]:
sel = ['총세대수', '전용면적', '전용면적별세대수',
       '공가수',  '단지내주차면수', '자격유형']

X = train[sel]
y = train['등록차량수']

# 데이터 나누기
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [40]:
model = LinearRegression()
model.fit(X_train, y_train)
pred = model.predict(X_test)

In [41]:
print("학습(score) :", model.score(X_train, y_train) ) # 결정계수
print("테스트(score) :", model.score(X_test, y_test) ) # 결정계수

# 정확도 평가
# mae
print(np.mean( np.abs(y_test - pred)))

# mse
mse_val = np.mean((y_test - pred)**2)
print(mse_val)

# rmse
print(np.sqrt(mse_val))

학습(score) : 0.7848278438379498
테스트(score) : 0.7841937560157191
147.8977567932893
43640.968133126094
208.9042080311598

In [44]:
all_df = pd.concat([train,test], join='inner')
all_df

,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,10분내지하철수,10분내버스정류장수,단지내주차면수,등록차량수
0,C2515,545,아파트,경상남도,국민임대,33.48,276,17.0,1,9216000,82940,0.0,3.0,624.0,205.000000
1,C2515,545,아파트,경상남도,국민임대,39.60,60,17.0,1,12672000,107130,0.0,3.0,624.0,205.000000
2,C2515,545,아파트,경상남도,국민임대,39.60,20,17.0,1,12672000,107130,0.0,3.0,624.0,205.000000
3,C2515,545,아파트,경상남도,국민임대,46.90,38,17.0,1,18433000,149760,0.0,3.0,624.0,205.000000
4,C2515,545,아파트,경상남도,국민임대,46.90,19,17.0,1,18433000,149760,0.0,3.0,624.0,205.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,C1267,675,아파트,경상남도,행복주택,36.77,126,38.0,12,-,-,0.0,1.0,467.0,497.389022
1004,C2189,382,아파트,전라북도,국민임대,29.19,96,45.0,8,6872000,106400,0.0,2.0,300.0,414.752412
1005,C2189,382,아파트,전라북도,국민임대,29.19,20,45.0,8,6872000,106400,0.0,2.0,300.0,414.752412
1006,C2189,382,아파트,전라북도,국민임대,39.45,202,45.0,8,13410000,144600,0.0,2.0,300.0,414.752412
1007,C2189,382,아파트,전라북도,국민임대,46.23,60,45.0,8,18689000,166500,0.0,2.0,300.0,414.752412

In [45]:
all_df['지역'].unique()

array(['경상남도', '대전광역시', '경기도', '전라북도', '강원도', '광주광역시', '충청남도', '부산광역시',
       '제주특별자치도', '울산광역시', '충청북도', '전라남도', '경상북도', '대구광역시', '서울특별시',
       '세종특별자치시'], dtype=object)

In [46]:
all_df.loc[all_df['자격유형'].isnull()]

Empty DataFrame
Columns: [단지코드, 총세대수, 임대건물구분, 지역, 공급유형, 전용면적, 전용면적별세대수, 공가수, 자격유형, 임대보증금, 임대료, 10분내지하철수, 10분내버스정류장수, 단지내주차면수, 등록차량수]
Index: []

In [47]:
all_df.isnull().sum()

단지코드            0
총세대수            0
임대건물구분          0
지역              0
공급유형            0
전용면적            0
전용면적별세대수        0
공가수             0
자격유형            0
임대보증금         749
임대료           749
10분내지하철수      249
10분내버스정류장수      0
단지내주차면수         0
등록차량수           0
dtype: int64

In [48]:
all_df.head()

,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,10분내지하철수,10분내버스정류장수,단지내주차면수,등록차량수
0,C2515,545,아파트,경상남도,국민임대,33.48,276,17.0,1,9216000,82940,0.0,3.0,624.0,205.0
1,C2515,545,아파트,경상남도,국민임대,39.60,60,17.0,1,12672000,107130,0.0,3.0,624.0,205.0
2,C2515,545,아파트,경상남도,국민임대,39.60,20,17.0,1,12672000,107130,0.0,3.0,624.0,205.0
3,C2515,545,아파트,경상남도,국민임대,46.90,38,17.0,1,18433000,149760,0.0,3.0,624.0,205.0
4,C2515,545,아파트,경상남도,국민임대,46.90,19,17.0,1,18433000,149760,0.0,3.0,624.0,205.0

In [49]:
gubun1 = {'아파트':1, '상가':2}
gubun2 = {'경상남도':1, '대전광역시':2, '경기도':3, '전라북도':4, '강원도':5,
          '광주광역시':6, '충청남도':7, '부산광역시':8, '제주특별자치도':9, '울산광역시':10,
          '충청북도':11, '전라남도':12, '경상북도':13, '대구광역시':14, '서울특별시':15, '세종특별자치시':16}
gubun3 = {'국민임대':1, '공공임대(50년)':2, '영구임대':3, '임대상가':4, '공공임대(10년)':5,
          '공공임대(분납)':6, '장기전세':7, '공공분양':8, '행복주택':9, '공공임대(5년)':10}
all_df['임대건물구분_lbl'] = all_df['임대건물구분'].map(gubun1)
all_df['지역_lbl'] = all_df['지역'].map(gubun2)
all_df['공급유형_lbl'] = all_df['공급유형'].map(gubun3)
all_df

,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,10분내지하철수,10분내버스정류장수,단지내주차면수,등록차량수,임대건물구분_lbl,지역_lbl,공급유형_lbl
0,C2515,545,아파트,경상남도,국민임대,33.48,276,17.0,1,9216000,82940,0.0,3.0,624.0,205.000000,1,1,1
1,C2515,545,아파트,경상남도,국민임대,39.60,60,17.0,1,12672000,107130,0.0,3.0,624.0,205.000000,1,1,1
2,C2515,545,아파트,경상남도,국민임대,39.60,20,17.0,1,12672000,107130,0.0,3.0,624.0,205.000000,1,1,1
3,C2515,545,아파트,경상남도,국민임대,46.90,38,17.0,1,18433000,149760,0.0,3.0,624.0,205.000000,1,1,1
4,C2515,545,아파트,경상남도,국민임대,46.90,19,17.0,1,18433000,149760,0.0,3.0,624.0,205.000000,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,C1267,675,아파트,경상남도,행복주택,36.77,126,38.0,12,-,-,0.0,1.0,467.0,497.389022,1,1,9
1004,C2189,382,아파트,전라북도,국민임대,29.19,96,45.0,8,6872000,106400,0.0,2.0,300.0,414.752412,1,4,1
1005,C2189,382,아파트,전라북도,국민임대,29.19,20,45.0,8,6872000,106400,0.0,2.0,300.0,414.752412,1,4,1
1006,C2189,382,아파트,전라북도,국민임대,39.45,202,45.0,8,13410000,144600,0.0,2.0,300.0,414.752412,1,4,1
1007,C2189,382,아파트,전라북도,국민임대,46.23,60,45.0,8,18689000,166500,0.0,2.0,300.0,414.752412,1,4,1

In [50]:
pd.set_option('display.max_rows', 500)  # 중간 생략 없이 500개 행은 다 보여준다.

In [51]:
grouped = train.groupby(['임대건물구분', '지역'])
group1 = grouped.get_group( ('아파트', '경상남도')  )
group1

,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,10분내지하철수,10분내버스정류장수,단지내주차면수,등록차량수
0,C2515,545,아파트,경상남도,국민임대,33.48,276,17.0,1,9216000,82940,0.0,3.0,624.0,205.0
1,C2515,545,아파트,경상남도,국민임대,39.60,60,17.0,1,12672000,107130,0.0,3.0,624.0,205.0
2,C2515,545,아파트,경상남도,국민임대,39.60,20,17.0,1,12672000,107130,0.0,3.0,624.0,205.0
3,C2515,545,아파트,경상남도,국민임대,46.90,38,17.0,1,18433000,149760,0.0,3.0,624.0,205.0
4,C2515,545,아파트,경상남도,국민임대,46.90,19,17.0,1,18433000,149760,0.0,3.0,624.0,205.0
5,C2515,545,아파트,경상남도,국민임대,51.97,106,17.0,1,23042000,190090,0.0,3.0,624.0,205.0
6,C2515,545,아파트,경상남도,국민임대,51.97,26,17.0,1,23042000,190090,0.0,3.0,624.0,205.0
84,C2576,405,아파트,경상남도,국민임대,46.90,313,19.0,1,19436000,161780,0.0,4.0,296.0,73.0
85,C2576,405,아파트,경상남도,국민임대,59.88,92,19.0,1,28252000,235420,0.0,4.0,296.0,73.0
123,C2416,560,아파트,경상남도,영구임대,26.34,360,0.0,3,3138000,69820,0.0,5.0,154.0,63.0
124,C2416,560,아파트,경상남도,영구임대,30.48,192,0.0,3,3631000,80800,0.0,5.0,154.0,63.0
133,C2013,595,아파트,경상남도,국민임대,36.02,90,3.0,1,13930000,37360,0.0,3.0,509.0,91.0
134,C2013,595,아파트,경상남도,국민임대,36.38,237,3.0,1,13930000,37360,0.0,3.0,509.0,91.0
135,C2013,595,아파트,경상남도,국민임대,45.88,267,3.0,1,17568000,45180,0.0,3.0,509.0,91.0
304,C1850,388,아파트,경상남도,공공임대(50년),39.74,89,0.0,1,11620000,212540,0.0,4.0,226.0,254.0
305,C1850,388,아파트,경상남도,공공임대(50년),49.62,178,0.0,1,14418000,244420,0.0,4.0,226.0,254.0
306,C1850,388,아파트,경상남도,공공임대(50년),49.62,118,0.0,1,14418000,244420,0.0,4.0,226.0,254.0
307,C2190,1013,아파트,경상남도,영구임대,26.37,191,7.0,3,3141000,69900,0.0,2.0,178.0,129.0
308,C2190,1013,아파트,경상남도,영구임대,26.37,358,7.0,3,3141000,69900,0.0,2.0,178.0,129.0
309,C2190,1013,아파트,경상남도,영구임대,26.37,298,7.0,3,3141000,69900,0.0,2.0,178.0,129.0
310,C2190,1013,아파트,경상남도,영구임대,31.32,149,7.0,3,3731000,83020,0.0,2.0,178.0,129.0
328,C1476,453,아파트,경상남도,영구임대,26.37,298,6.0,3,8133000,123200,0.0,5.0,107.0,70.0
329,C1476,453,아파트,경상남도,영구임대,31.32,149,6.0,3,9261000,136000,0.0,5.0,107.0,70.0
336,C1077,861,아파트,경상남도,국민임대,36.65,258,21.0,1,12483000,84880,0.0,5.0,612.0,236.0
337,C1077,861,아파트,경상남도,국민임대,46.90,277,21.0,1,19973000,147300,0.0,5.0,612.0,236.0
338,C1077,861,아파트,경상남도,국민임대,51.93,326,21.0,1,23720000,184760,0.0,5.0,612.0,236.0
614,C1899,451,아파트,경상남도,영구임대,26.37,298,0.0,3,7721000,117060,0.0,4.0,109.0,31.0
615,C1899,451,아파트,경상남도,영구임대,31.32,149,0.0,3,8775000,129200,0.0,4.0,109.0,31.0
691,C1790,657,아파트,경상남도,영구임대,26.37,239,2.0,3,3141000,69900,0.0,4.0,166.0,120.0
692,C1790,657,아파트,경상남도,영구임대,31.32,239,2.0,3,3731000,83020,0.0,4.0,166.0,120.0
693,C1790,657,아파트,경상남도,영구임대,31.32,149,2.0,3,3731000,83020,0.0,4.0,166.0,120.0
724,C2109,495,아파트,경상남도,영구임대,26.34,288,2.0,3,3138000,69820,0.0,4.0,117.0,60.0
725,C2109,495,아파트,경상남도,영구임대,30.48,192,2.0,3,3631000,80800,0.0,4.0,117.0,60.0
741,C1698,460,아파트,경상남도,영구임대,39.00,60,1.0,3,12864000,162030,0.0,3.0,155.0,65.0
742,C1698,460,아파트,경상남도,영구임대,39.00,120,1.0,3,12864000,162030,0.0,3.0,155.0,65.0
743,C1698,460,아파트,경상남도,영구임대,39.39,156,1.0,3,12864000,162030,0.0,3.0,155.0,65.0
744,C1698,460,아파트,경상남도,영구임대,39.39,120,1.0,3,12864000,162030,0.0,3.0,155.0,65.0
749,C1866,338,아파트,경상남도,국민임대,36.63,195,1.0,1,9592000,70740,0.0,3.0,235.0,135.0
750,C1866,338,아파트,경상남도,국민임대,39.51,36,1.0,1,10279000,84510,0.0,3.0,235.0,135.0
751,C1866,338,아파트,경상남도,국민임대,46.18,36,1.0,1,12563000,119920,0.0,3.0,235.0,135.0
752,C1866,338,아파트,경상남도,국민임대,46.71,71,1.0,1,12563000,119920,0.0,3.0,235.0,135.0
817,C2571,481,아파트,경상남도,영구임대,26.37,468,5.0,3,3056000,68000,0.0,1.0,65.0,62.0
911,C1867,678,아파트,경상남도,국민임대,36.52,216,26.0,1,9972000,100920,0.0,2.0,579.0,374.0
912,C1867,678,아파트,경상남도,국민임대,36.52,72,26.0,1,9972000,100920,0.0,2.0,579.0,374.0
913,C1867,678,아파트,경상남도,국민임대,36.52,124,26.0,1,9972000,100920,0.0,2.0,579.0,374.0
914,C1867,678,아파트,경상남도,국민임대,36.52,42,26.0,1,9972000,100920,0.0,2.0,579.0,374.0
915,C1867,678,아파트,경상남도,국민임대,46.54,84,26.0,1,17423000,144180,0.0,2.0,579.0,374.0
916,C1867,678,아파트,경상남도,국민임대,51.93,140,26.0,1,21027000,186230,0.0,2.0,579.0,374.0
940,C2000,1300,아파트,경상남도,국민임대,36.65,240,21.0,1,10813000,90110,0.0,2.0,1082.0,795.0
941,C2000,1300,아파트,경상남도,국민임대,36.65,30,21.0,1,10813000,90110,0.0,2.0,1082.0,795.0
942,C2000,1300,아파트,경상남도,국민임대,39.48,180,21.0,1,13697000,114140,0.0,2.0,1082.0,795.0
943,C2000,1300,아파트,경상남도,국민임대,46.90,135,21.0,1,19225000,169420,0.0,2.0,1082.0,795.0
944,C2000,1300,아파트,경상남도,국민임대,46.90,496,21.0,1,19225000,169420,0.0,2.0,1082.0,795.0
945,C2000,1300,아파트,경상남도,국민임대,46.90,69,21.0,1,19225000,169420,0.0,2.0,1082.0,795.0
946,C2000,1300,아파트,경상남도,국민임대,59.88,150,21.0,1,26435000,219880,0.0,2.0,1082.0,795.0
973,C2514,501,아파트,경상남도,국민임대,46.69,44,10.0,1,13625000,138720,0.0,1.0,405.0,648.0
974,C2514,501,아파트,경상남도,국민임대,46.90,156,10.0,1,13625000,138720,0.0,1.0,405.0,648.0
975,C2514,501,아파트,경상남도,국민임대,46.90,24,10.0,1,13625000,138720,0.0,1.0,405.0,648.0
976,C2514,501,아파트,경상남도,국민임대,51.92,44,10.0,1,17342000,161020,0.0,1.0,405.0,648.0
977,C2514,501,아파트,경상남도,국민임대,51.93,198,10.0,1,17342000,161020,0.0,1.0,405.0,648.0
978,C2514,501,아파트,경상남도,국민임대,51.93,35,10.0,1,17342000,161020,0.0,1.0,405.0,648.0
996,C2256,409,아파트,경상남도,국민임대,29.91,88,7.0,1,8394000,65950,0.0,1.0,316.0,344.0
997,C2256,409,아파트,경상남도,국민임대,36.62,131,7.0,1,9592000,91140,0.0,1.0,316.0,344.0
998,C2256,409,아파트,경상남도,국민임대,46.90,132,7.0,1,15590000,136710,0.0,1.0,316.0,344.0
999,C2256,409,아파트,경상남도,국민임대,51.93,40,7.0,1,19187000,167890,0.0,1.0,316.0,344.0
1000,C2256,409,아파트,경상남도,국민임대,51.93,18,7.0,1,19187000,167890,0.0,1.0,316.0,344.0
1113,C2032,944,아파트,경상남도,국민임대,51.78,135,23.0,1,24969000,149810,0.0,1.0,958.0,1162.0
1114,C2032,944,아파트,경상남도,국민임대,51.78,22,23.0,1,24969000,149810,0.0,1.0,958.0,1162.0
1115,C2032,944,아파트,경상남도,국민임대,59.85,102,23.0,1,31210000,187260,0.0,1.0,958.0,1162.0
1116,C2032,944,아파트,경상남도,국민임대,59.85,178,23.0,1,31210000,187260,0.0,1.0,958.0,1162.0
1117,C2032,944,아파트,경상남도,국민임대,59.89,82,23.0,1,31210000,187260,0.0,1.0,958.0,1162.0
1118,C2032,944,아파트,경상남도,국민임대,59.92,157,23.0,1,31210000,187260,0.0,1.0,958.0,1162.0
1119,C2032,944,아파트,경상남도,국민임대,59.92,224,23.0,1,31210000,187260,0.0,1.0,958.0,1162.0
1120,C2032,944,아파트,경상남도,국민임대,59.95,44,23.0,1,31210000,187260,0.0,1.0,958.0,1162.0
1121,C2094,410,아파트,경상남도,국민임대,36.22,90,16.0,1,13633000,101830,0.0,20.0,402.0,318.0
1122,C2094,410,아파트,경상남도,국민임대,36.22,36,16.0,1,13633000,101830,0.0,20.0,402.0,318.0
1123,C2094,410,아파트,경상남도,국민임대,39.15,64,16.0,1,14742000,107060,0.0,20.0,402.0,318.0
1124,C2094,410,아파트,경상남도,국민임대,39.15,33,16.0,1,14742000,107060,0.0,20.0,402.0,318.0
1125,C2094,410,아파트,경상남도,국민임대,46.47,97,16.0,1,17499000,116200,0.0,20.0,402.0,318.0
1126,C2094,410,아파트,경상남도,국민임대,46.48,60,16.0,1,17499000,116200,0.0,20.0,402.0,318.0
1127,C2094,410,아파트,경상남도,국민임대,46.48,30,16.0,1,17499000,116200,0.0,20.0,402.0,318.0
1128,C1880,635,아파트,경상남도,국민임대,51.86,422,15.0,1,22628000,131980,0.0,20.0,508.0,761.0
1129,C1880,635,아파트,경상남도,국민임대,51.92,31,15.0,1,22628000,131980,0.0,20.0,508.0,761.0
1130,C1880,635,아파트,경상남도,국민임대,51.96,66,15.0,1,22628000,131980,0.0,20.0,508.0,761.0
1131,C1880,635,아파트,경상남도,국민임대,59.99,116,15.0,1,27657000,148320,0.0,20.0,508.0,761.0
1132,C2089,962,아파트,경상남도,국민임대,39.72,255,27.0,1,13625000,123870,0.0,1.0,873.0,572.0
1133,C2089,962,아파트,경상남도,국민임대,39.72,90,27.0,1,13625000,123870,0.0,1.0,873.0,572.0
1134,C2089,962,아파트,경상남도,국민임대,39.73,128,27.0,1,13625000,123870,0.0,1.0,873.0,572.0
1135,C2089,962,아파트,경상남도,국민임대,46.90,129,27.0,1,19819000,136250,0.0,1.0,873.0,572.0
1136,C2089,962,아파트,경상남도,국민임대,51.93,120,27.0,1,23536000,148630,0.0,1.0,873.0,572.0
1137,C2089,962,아파트,경상남도,국민임대,51.93,240,27.0,1,23536000,148630,0.0,1.0,873.0,572.0
1245,C1319,496,아파트,경상남도,국민임대,29.96,82,16.0,1,8738000,74890,0.0,1.0,428.0,398.0
1246,C1319,496,아파트,경상남도,국민임대,36.80,156,16.0,1,9985000,99850,0.0,1.0,428.0,398.0
1247,C1319,496,아파트,경상남도,국민임대,36.80,48,16.0,1,9985000,99850,0.0,1.0,428.0,398.0
1248,C1319,496,아파트,경상남도,국민임대,46.06,82,16.0,1,17477000,146060,0.0,1.0,428.0,398.0
1249,C1319,496,아파트,경상남도,국민임대,50.83,88,16.0,1,21221000,178510,0.0,1.0,428.0,398.0
1250,C1319,496,아파트,경상남도,국민임대,50.83,40,16.0,1,21221000,178510,0.0,1.0,428.0,398.0
1251,C1141,630,아파트,경상남도,국민임대,36.72,60,28.0,1,11380000,74590,0.0,2.0,637.0,620.0
1252,C1141,630,아파트,경상남도,국민임대,39.49,129,28.0,1,11380000,83430,0.0,2.0,637.0,620.0
1253,C1141,630,아파트,경상남도,국민임대,46.45,129,28.0,1,13909000,98630,0.0,2.0,637.0,620.0
1254,C1141,630,아파트,경상남도,국민임대,46.96,30,28.0,1,13909000,98630,0.0,2.0,637.0,620.0
1255,C1141,630,아파트,경상남도,국민임대,51.86,162,28.0,1,18968000,113800,0.0,2.0,637.0,620.0
1256,C1141,630,아파트,경상남도,국민임대,59.99,120,28.0,1,22763000,126460,0.0,2.0,637.0,620.0
1371,C2358,1260,아파트,경상남도,국민임대,36.61,401,24.0,1,15577000,88260,0.0,8.0,941.0,1010.0
1372,C2358,1260,아파트,경상남도,국민임대,36.61,141,24.0,1,15577000,88260,0.0,8.0,941.0,1010.0
1373,C2358,1260,아파트,경상남도,국민임대,36.61,12,24.0,1,15577000,88260,0.0,8.0,941.0,1010.0
1374,C2358,1260,아파트,경상남도,국민임대,46.29,603,24.0,1,24665000,166140,0.0,8.0,941.0,1010.0
1375,C2358,1260,아파트,경상남도,국민임대,46.29,91,24.0,1,24665000,166140,0.0,8.0,941.0,1010.0
1376,C2358,1260,아파트,경상남도,국민임대,46.29,12,24.0,1,24665000,166140,0.0,8.0,941.0,1010.0
1563,C1375,757,아파트,경상남도,국민임대,46.90,141,21.0,1,22471000,137310,0.0,12.0,761.0,754.0
1564,C1375,757,아파트,경상남도,국민임대,46.90,95,21.0,1,22471000,137310,0.0,12.0,761.0,754.0
1565,C1375,757,아파트,경상남도,국민임대,46.91,63,21.0,1,22471000,137310,0.0,12.0,761.0,754.0
1566,C1375,757,아파트,경상남도,국민임대,46.91,31,21.0,1,22471000,137310,0.0,12.0,761.0,754.0
1567,C1375,757,아파트,경상남도,국민임대,51.93,29,21.0,1,24969000,149810,0.0,12.0,761.0,754.0
1568,C1375,757,아파트,경상남도,국민임대,51.93,19,21.0,1,24969000,149810,0.0,12.0,761.0,754.0
1569,C1375,757,아파트,경상남도,국민임대,59.88,379,21.0,1,31210000,187260,0.0,12.0,761.0,754.0
1573,C1641,283,아파트,경상남도,국민임대,36.62,90,8.0,1,8435000,71380,0.0,1.0,227.0,268.0
1574,C1641,283,아파트,경상남도,국민임대,46.90,86,8.0,1,11682000,103840,0.0,1.0,227.0,268.0
1575,C1641,283,아파트,경상남도,국민임대,51.93,87,8.0,1,14278000,124610,0.0,1.0,227.0,268.0
1576,C1641,283,아파트,경상남도,국민임대,51.93,20,8.0,1,14278000,124610,0.0,1.0,227.0,268.0
1693,C2680,758,아파트,경상남도,국민임대,36.63,486,19.0,1,20233000,98630,0.0,7.0,564.0,590.0
1694,C2680,758,아파트,경상남도,국민임대,46.71,149,19.0,1,25293000,145410,0.0,7.0,564.0,590.0
1695,C2680,758,아파트,경상남도,국민임대,46.71,123,19.0,1,25293000,145410,0.0,7.0,564.0,590.0
1696,C2631,812,아파트,경상남도,국민임대,39.49,127,2.0,1,14487000,88120,0.0,3.0,612.0,638.0
1697,C2631,812,아파트,경상남도,국민임대,39.88,135,2.0,1,14487000,88120,0.0,3.0,612.0,638.0
1698,C2631,812,아파트,경상남도,국민임대,39.88,60,2.0,1,14487000,88120,0.0,3.0,612.0,638.0
1699,C2631,812,아파트,경상남도,국민임대,46.45,129,2.0,1,20525000,102620,0.0,3.0,612.0,638.0
1700,C2631,812,아파트,경상남도,국민임대,46.96,45,2.0,1,20525000,102620,0.0,3.0,612.0,638.0
1701,C2631,812,아파트,경상남도,국민임대,46.96,30,2.0,1,20525000,102620,0.0,3.0,612.0,638.0
1702,C2631,812,아파트,경상남도,국민임대,51.86,286,2.0,1,27044000,120730,0.0,3.0,612.0,638.0
1703,C2141,504,아파트,경상남도,국민임대,36.62,120,2.0,1,18581000,136250,0.0,6.0,445.0,495.0
1704,C2141,504,아파트,경상남도,국민임대,41.99,120,2.0,1,24775000,185810,0.0,6.0,445.0,495.0
1705,C2141,504,아파트,경상남도,국민임대,46.90,120,2.0,1,30969000,247750,0.0,6.0,445.0,495.0
1706,C2141,504,아파트,경상남도,국민임대,46.90,144,2.0,1,30969000,247750,0.0,6.0,445.0,495.0
1707,C1569,631,아파트,경상남도,국민임대,36.19,43,8.0,1,12571000,87980,0.0,3.0,442.0,528.0
1708,C1569,631,아파트,경상남도,국민임대,36.23,46,8.0,1,12571000,87980,0.0,3.0,442.0,528.0
1709,C1569,631,아파트,경상남도,국민임대,36.30,23,8.0,1,12571000,87980,0.0,3.0,442.0,528.0
1710,C1569,631,아파트,경상남도,국민임대,36.63,227,8.0,1,12571000,87980,0.0,3.0,442.0,528.0
1711,C1569,631,아파트,경상남도,국민임대,36.63,53,8.0,1,12571000,87980,0.0,3.0,442.0,528.0
1712,C1569,631,아파트,경상남도,국민임대,46.22,200,8.0,1,16341000,108080,0.0,3.0,442.0,528.0
1713,C1569,631,아파트,경상남도,국민임대,46.22,39,8.0,1,16341000,108080,0.0,3.0,442.0,528.0
1761,C1660,718,아파트,경상남도,국민임대,39.51,90,13.0,1,11175000,85020,0.0,3.0,550.0,512.0
1762,C1660,718,아파트,경상남도,국민임대,39.84,60,13.0,1,11175000,85020,0.0,3.0,550.0,512.0
1763,C1660,718,아파트,경상남도,국민임대,39.84,30,13.0,1,11175000,85020,0.0,3.0,550.0,512.0
1764,C1660,718,아파트,경상남도,국민임대,46.18,88,13.0,1,14213000,94750,0.0,3.0,550.0,512.0
1765,C1660,718,아파트,경상남도,국민임대,46.71,60,13.0,1,14213000,94750,0.0,3.0,550.0,512.0
1766,C1660,718,아파트,경상남도,국민임대,46.71,30,13.0,1,14213000,94750,0.0,3.0,550.0,512.0
1767,C1660,718,아파트,경상남도,국민임대,51.71,240,13.0,1,21259000,127540,0.0,3.0,550.0,512.0
1768,C1660,718,아파트,경상남도,국민임대,59.99,120,13.0,1,24297000,145780,0.0,3.0,550.0,512.0
1779,C1994,431,아파트,경상남도,국민임대,46.84,114,3.0,1,13760000,98820,0.0,1.0,319.0,496.0
1780,C1994,431,아파트,경상남도,국민임대,46.84,89,3.0,1,13760000,98820,0.0,1.0,319.0,496.0
1781,C1994,431,아파트,경상남도,국민임대,51.93,149,3.0,1,18767000,112590,0.0,1.0,319.0,496.0
1782,C1994,431,아파트,경상남도,국민임대,51.93,79,3.0,1,18767000,112590,0.0,1.0,319.0,496.0
1783,C1837,467,아파트,경상남도,국민임대,33.48,159,21.0,1,9290000,92900,0.0,4.0,366.0,398.0
1784,C1837,467,아파트,경상남도,국민임대,33.48,73,21.0,1,9290000,92900,0.0,4.0,366.0,398.0
1785,C1837,467,아파트,경상남도,국민임대,46.90,78,21.0,1,18075000,144590,0.0,4.0,366.0,398.0
1786,C1837,467,아파트,경상남도,국민임대,46.90,39,21.0,1,18075000,144590,0.0,4.0,366.0,398.0
1787,C1837,467,아파트,경상남도,국민임대,51.97,60,21.0,1,21690000,168700,0.0,4.0,366.0,398.0
1788,C1837,467,아파트,경상남도,국민임대,51.97,58,21.0,1,21690000,168700,0.0,4.0,366.0,398.0
1881,C1227,806,아파트,경상남도,국민임대,29.95,75,7.0,1,12015000,151380,0.0,1.0,707.0,823.0
1882,C1227,806,아파트,경상남도,국민임대,29.96,85,7.0,1,12015000,151380,0.0,1.0,707.0,823.0
1883,C1227,806,아파트,경상남도,국민임대,36.81,295,7.0,1,14418000,198250,0.0,1.0,707.0,823.0
1884,C1227,806,아파트,경상남도,국민임대,36.81,40,7.0,1,14418000,198250,0.0,1.0,707.0,823.0
1885,C1227,806,아파트,경상남도,국민임대,46.73,16,7.0,1,32443000,264350,0.0,1.0,707.0,823.0
1886,C1227,806,아파트,경상남도,국민임대,46.73,16,7.0,1,32443000,264350,0.0,1.0,707.0,823.0
1887,C1227,806,아파트,경상남도,국민임대,46.92,75,7.0,1,32443000,264350,0.0,1.0,707.0,823.0
1888,C1227,806,아파트,경상남도,국민임대,51.87,146,7.0,1,36048000,324430,0.0,1.0,707.0,823.0
1889,C1227,806,아파트,경상남도,국민임대,51.87,58,7.0,1,36048000,324430,0.0,1.0,707.0,823.0
1896,C2486,589,아파트,경상남도,국민임대,29.95,44,2.0,1,12015000,151380,0.0,4.0,515.0,587.0
1897,C2486,589,아파트,경상남도,국민임대,29.96,65,2.0,1,12015000,151380,0.0,4.0,515.0,587.0
1898,C2486,589,아파트,경상남도,국민임대,36.81,201,2.0,1,14418000,198250,0.0,4.0,515.0,587.0
1899,C2486,589,아파트,경상남도,국민임대,36.81,20,2.0,1,14418000,198250,0.0,4.0,515.0,587.0
1900,C2486,589,아파트,경상남도,국민임대,36.81,18,2.0,1,14418000,198250,0.0,4.0,515.0,587.0
1901,C2486,589,아파트,경상남도,국민임대,46.73,20,2.0,1,32443000,264350,0.0,4.0,515.0,587.0
1902,C2486,589,아파트,경상남도,국민임대,46.73,20,2.0,1,32443000,264350,0.0,4.0,515.0,587.0
1903,C2486,589,아파트,경상남도,국민임대,46.92,44,2.0,1,32443000,264350,0.0,4.0,515.0,587.0
1904,C2486,589,아파트,경상남도,국민임대,51.87,106,2.0,1,36048000,324430,0.0,4.0,515.0,587.0
1905,C2486,589,아파트,경상남도,국민임대,51.87,51,2.0,1,36048000,324430,0.0,4.0,515.0,587.0
1911,C1572,937,아파트,경상남도,국민임대,33.55,88,32.0,1,11174000,93710,0.0,3.0,770.0,479.0
1912,C1572,937,아파트,경상남도,국민임대,33.55,294,32.0,1,11174000,93710,0.0,3.0,770.0,479.0
1913,C1572,937,아파트,경상남도,국민임대,36.74,68,32.0,1,12254000,102130,0.0,3.0,770.0,479.0
1914,C1572,937,아파트,경상남도,국민임대,36.74,140,32.0,1,12254000,102130,0.0,3.0,770.0,479.0
1915,C1572,937,아파트,경상남도,국민임대,46.43,234,32.0,5,76089000,39620,0.0,3.0,770.0,479.0
1916,C1572,937,아파트,경상남도,국민임대,51.55,113,32.0,5,93486000,48690,0.0,3.0,770.0,479.0
1966,C2127,700,아파트,경상남도,국민임대,39.57,240,21.0,1,15130000,127650,0.0,2.0,592.0,403.0
1967,C2127,700,아파트,경상남도,국민임대,39.57,112,21.0,1,15130000,127650,0.0,2.0,592.0,403.0
1968,C2127,700,아파트,경상남도,국민임대,46.90,60,21.0,1,20802000,174930,0.0,2.0,592.0,403.0
1969,C2127,700,아파트,경상남도,국민임대,46.90,60,21.0,1,20802000,174930,0.0,2.0,592.0,403.0
1970,C2127,700,아파트,경상남도,국민임대,46.90,108,21.0,1,20802000,174930,0.0,2.0,592.0,403.0
1971,C2127,700,아파트,경상남도,국민임대,51.35,120,21.0,1,25415000,210410,0.0,2.0,592.0,403.0
1980,C1713,656,아파트,경상남도,국민임대,36.50,196,2.0,1,10923000,117270,0.0,1.0,527.0,566.0
1981,C1713,656,아파트,경상남도,국민임대,36.50,84,2.0,1,10923000,117270,0.0,1.0,527.0,566.0
1982,C1713,656,아파트,경상남도,국민임대,36.50,129,2.0,1,10923000,117270,0.0,1.0,527.0,566.0
1983,C1713,656,아파트,경상남도,국민임대,36.50,45,2.0,1,10923000,117270,0.0,1.0,527.0,566.0
1984,C1713,656,아파트,경상남도,국민임대,46.54,90,2.0,1,19892000,166730,0.0,1.0,527.0,566.0
1985,C1713,656,아파트,경상남도,국민임대,51.93,112,2.0,1,24837000,208120,0.0,1.0,527.0,566.0
2082,C1738,715,아파트,경상남도,국민임대,36.88,120,13.0,1,11729000,100380,0.0,3.0,582.0,682.0
2083,C1738,715,아파트,경상남도,국민임대,36.88,360,13.0,1,11729000,100380,0.0,3.0,582.0,682.0
2084,C1738,715,아파트,경상남도,국민임대,46.98,156,13.0,1,20847000,149220,0.0,3.0,582.0,682.0
2085,C1738,715,아파트,경상남도,국민임대,51.69,79,13.0,1,24139000,184330,0.0,3.0,582.0,682.0
2158,C1788,376,아파트,경상남도,공공임대(10년),51.59,116,28.0,1,29000000,340000,0.0,3.0,380.0,412.0
2159,C1788,376,아파트,경상남도,공공임대(10년),59.97,260,28.0,1,36000000,390000,0.0,3.0,380.0,412.0
2208,C2405,600,아파트,경상남도,공공임대(10년),75.84,48,22.0,1,36019000,603480,0.0,8.0,728.0,1240.0
2209,C2405,600,아파트,경상남도,공공임대(10년),75.99,54,22.0,1,36113000,603480,0.0,8.0,728.0,1240.0
2210,C2405,600,아파트,경상남도,공공임대(10년),84.95,182,22.0,1,44868000,636400,0.0,8.0,728.0,1240.0
2293,N2431,1047,아파트,경상남도,공공임대(10년),74.97,80,15.0,1,46000000,456000,NaN,5.0,1066.0,1214.0
2294,N2431,1047,아파트,경상남도,공공임대(10년),84.95,124,15.0,1,57000000,462000,NaN,5.0,1066.0,1214.0
2295,N2431,1047,아파트,경상남도,공공임대(10년),84.96,289,15.0,1,57000000,462000,NaN,5.0,1066.0,1214.0
2296,N2431,1047,아파트,경상남도,공공임대(10년),84.98,82,15.0,1,57000000,462000,NaN,5.0,1066.0,1214.0
2339,C1027,452,아파트,경상남도,국민임대,33.83,174,21.0,1,11370000,203220,0.0,5.0,461.0,207.0
2340,C1027,452,아파트,경상남도,국민임대,39.56,88,21.0,1,19171000,246230,0.0,5.0,461.0,207.0
2341,C1027,452,아파트,경상남도,국민임대,46.63,138,21.0,1,26851000,306450,0.0,5.0,461.0,207.0
2342,C1027,452,아파트,경상남도,국민임대,46.63,30,21.0,1,26851000,306450,0.0,5.0,461.0,207.0
2343,C1027,452,아파트,경상남도,국민임대,46.95,22,21.0,1,26851000,306450,0.0,5.0,461.0,207.0
2344,C2377,1105,아파트,경상남도,국민임대,33.83,408,22.0,1,11269000,202140,0.0,3.0,1110.0,579.0
2345,C2377,1105,아파트,경상남도,국민임대,39.56,366,22.0,1,19014000,246230,0.0,3.0,1110.0,579.0
2346,C2377,1105,아파트,경상남도,국민임대,46.63,96,22.0,1,26673000,305370,0.0,3.0,1110.0,579.0
2347,C2377,1105,아파트,경상남도,국민임대,46.95,44,22.0,1,26673000,305370,0.0,3.0,1110.0,579.0
2348,C2377,1105,아파트,경상남도,국민임대,51.96,146,22.0,1,30112000,331180,0.0,3.0,1110.0,579.0
2349,C2377,1105,아파트,경상남도,국민임대,51.96,45,22.0,1,30112000,331180,0.0,3.0,1110.0,579.0
2350,N2431,1047,아파트,경상남도,국민임대,36.77,272,16.0,1,11217000,233330,0.0,2.0,1066.0,1214.0
2351,N2431,1047,아파트,경상남도,국민임대,46.78,200,16.0,1,24389000,303220,0.0,2.0,1066.0,1214.0
2494,C1320,1696,아파트,경상남도,국민임대,26.80,616,35.0,8,7870000,154000,0.0,4.0,1648.0,924.0
2495,C1320,1696,아파트,경상남도,국민임대,33.88,728,35.0,8,9930000,184000,0.0,4.0,1648.0,924.0
2496,C1320,1696,아파트,경상남도,국민임대,46.93,184,35.0,8,23640000,290000,0.0,4.0,1648.0,924.0
2497,C1320,1696,아파트,경상남도,국민임대,46.93,168,35.0,8,23640000,290000,0.0,4.0,1648.0,924.0
2498,C1941,404,아파트,경상남도,공공임대(10년),84.94,64,19.0,1,47288000,627080,0.0,3.0,490.0,600.0
2499,C1941,404,아파트,경상남도,공공임대(10년),84.94,72,19.0,1,47288000,627080,0.0,3.0,490.0,600.0
2500,C1941,404,아파트,경상남도,공공임대(10년),84.96,16,19.0,1,47288000,627080,0.0,3.0,490.0,600.0
2501,C1941,404,아파트,경상남도,공공임대(10년),84.99,252,19.0,1,47288000,627080,0.0,3.0,490.0,600.0
2538,C1258,840,아파트,경상남도,국민임대,26.83,224,0.0,8,9672000,128000,0.0,3.0,658.0,616.0
2539,C1258,840,아파트,경상남도,국민임대,26.90,36,0.0,8,9672000,128000,0.0,3.0,658.0,616.0
2540,C1258,840,아파트,경상남도,국민임대,37.70,330,0.0,8,18624000,182000,0.0,3.0,658.0,616.0
2541,C1258,840,아파트,경상남도,국민임대,46.94,110,0.0,8,29054000,240000,0.0,3.0,658.0,616.0
2542,C1258,840,아파트,경상남도,영구임대,24.72,122,0.0,9,7973000,72200,0.0,3.0,658.0,616.0
2543,C1258,840,아파트,경상남도,영구임대,24.79,18,0.0,9,7973000,72200,0.0,3.0,658.0,616.0
2564,C1724,1256,아파트,경상남도,국민임대,31.65,210,1.0,8,9859000,172000,0.0,6.0,878.0,701.0
2565,C1724,1256,아파트,경상남도,영구임대,24.74,80,1.0,9,8112000,81000,0.0,6.0,878.0,701.0
2566,C1724,1256,아파트,경상남도,행복주택,21.54,22,1.0,12,20460000,100000,0.0,6.0,878.0,701.0
2567,C1724,1256,아파트,경상남도,행복주택,21.54,97,1.0,12,20460000,100000,0.0,6.0,878.0,701.0
2568,C1724,1256,아파트,경상남도,행복주택,21.54,33,1.0,12,20460000,100000,0.0,6.0,878.0,701.0
2569,C1724,1256,아파트,경상남도,행복주택,21.90,234,1.0,12,21220000,104000,0.0,6.0,878.0,701.0
2570,C1724,1256,아파트,경상남도,행복주택,26.27,344,1.0,12,24660000,121000,0.0,6.0,878.0,701.0
2571,C1724,1256,아파트,경상남도,행복주택,26.37,40,1.0,12,24660000,121000,0.0,6.0,878.0,701.0
2572,C1724,1256,아파트,경상남도,행복주택,36.78,172,1.0,12,34140000,167000,0.0,6.0,878.0,701.0

In [52]:
train.corr()

,총세대수,전용면적,전용면적별세대수,공가수,자격유형,10분내지하철수,10분내버스정류장수,단지내주차면수,등록차량수
총세대수,1.000000,0.040103,0.098876,0.066245,0.172269,0.211792,-0.002570,0.522593,0.333440
전용면적,0.040103,1.000000,-0.032453,-0.081549,-0.167612,-0.010291,-0.004269,0.067340,0.112717
전용면적별세대수,0.098876,-0.032453,1.000000,0.162061,-0.075550,-0.057606,0.045578,0.283585,0.250513
공가수,0.066245,-0.081549,0.162061,1.000000,0.210929,-0.094096,0.044062,0.288062,0.118910
자격유형,0.172269,-0.167612,-0.075550,0.210929,1.000000,0.009012,-0.032659,-0.063684,-0.154482
10분내지하철수,0.211792,-0.010291,-0.057606,-0.094096,0.009012,1.000000,0.097503,-0.053185,-0.107308
10분내버스정류장수,-0.002570,-0.004269,0.045578,0.044062,-0.032659,0.097503,1.000000,0.073722,0.104964
단지내주차면수,0.522593,0.067340,0.283585,0.288062,-0.063684,-0.053185,0.073722,1.000000,0.861338
등록차량수,0.333440,0.112717,0.250513,0.118910,-0.154482,-0.107308,0.104964,0.861338,1.000000

In [53]:
all_df.loc[all_df['10분내버스정류장수'].isnull(), '10분내버스정류장수']=5

In [54]:
all_df.loc[all_df['10분내버스정류장수'].isnull(), :]

Empty DataFrame
Columns: [단지코드, 총세대수, 임대건물구분, 지역, 공급유형, 전용면적, 전용면적별세대수, 공가수, 자격유형, 임대보증금, 임대료, 10분내지하철수, 10분내버스정류장수, 단지내주차면수, 등록차량수, 임대건물구분_lbl, 지역_lbl, 공급유형_lbl]
Index: []

In [55]:
all_df['단지코드'] = all_df['단지코드'].astype("category")
all_df['단지코드_lbl'] = all_df['단지코드'].cat.codes  # 문자열 코드를 숫자로 바꿔주는 방법 중 하나
all_df

,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,10분내지하철수,10분내버스정류장수,단지내주차면수,등록차량수,임대건물구분_lbl,지역_lbl,공급유형_lbl,단지코드_lbl
0,C2515,545,아파트,경상남도,국민임대,33.48,276,17.0,1,9216000,82940,0.0,3.0,624.0,205.000000,1,1,1,492
1,C2515,545,아파트,경상남도,국민임대,39.60,60,17.0,1,12672000,107130,0.0,3.0,624.0,205.000000,1,1,1,492
2,C2515,545,아파트,경상남도,국민임대,39.60,20,17.0,1,12672000,107130,0.0,3.0,624.0,205.000000,1,1,1,492
3,C2515,545,아파트,경상남도,국민임대,46.90,38,17.0,1,18433000,149760,0.0,3.0,624.0,205.000000,1,1,1,492
4,C2515,545,아파트,경상남도,국민임대,46.90,19,17.0,1,18433000,149760,0.0,3.0,624.0,205.000000,1,1,1,492
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,C1267,675,아파트,경상남도,행복주택,36.77,126,38.0,12,-,-,0.0,1.0,467.0,497.389022,1,1,9,86
1004,C2189,382,아파트,전라북도,국민임대,29.19,96,45.0,8,6872000,106400,0.0,2.0,300.0,414.752412,1,4,1,381
1005,C2189,382,아파트,전라북도,국민임대,29.19,20,45.0,8,6872000,106400,0.0,2.0,300.0,414.752412,1,4,1,381
1006,C2189,382,아파트,전라북도,국민임대,39.45,202,45.0,8,13410000,144600,0.0,2.0,300.0,414.752412,1,4,1,381
1007,C2189,382,아파트,전라북도,국민임대,46.23,60,45.0,8,18689000,166500,0.0,2.0,300.0,414.752412,1,4,1,381

In [56]:
all_df_last = all_df.drop(['임대건물구분', '지역', '공급유형'], axis=1)
all_df_last

,단지코드,총세대수,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,10분내지하철수,10분내버스정류장수,단지내주차면수,등록차량수,임대건물구분_lbl,지역_lbl,공급유형_lbl,단지코드_lbl
0,C2515,545,33.48,276,17.0,1,9216000,82940,0.0,3.0,624.0,205.000000,1,1,1,492
1,C2515,545,39.60,60,17.0,1,12672000,107130,0.0,3.0,624.0,205.000000,1,1,1,492
2,C2515,545,39.60,20,17.0,1,12672000,107130,0.0,3.0,624.0,205.000000,1,1,1,492
3,C2515,545,46.90,38,17.0,1,18433000,149760,0.0,3.0,624.0,205.000000,1,1,1,492
4,C2515,545,46.90,19,17.0,1,18433000,149760,0.0,3.0,624.0,205.000000,1,1,1,492
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,C1267,675,36.77,126,38.0,12,-,-,0.0,1.0,467.0,497.389022,1,1,9,86
1004,C2189,382,29.19,96,45.0,8,6872000,106400,0.0,2.0,300.0,414.752412,1,4,1,381
1005,C2189,382,29.19,20,45.0,8,6872000,106400,0.0,2.0,300.0,414.752412,1,4,1,381
1006,C2189,382,39.45,202,45.0,8,13410000,144600,0.0,2.0,300.0,414.752412,1,4,1,381
1007,C2189,382,46.23,60,45.0,8,18689000,166500,0.0,2.0,300.0,414.752412,1,4,1,381

In [59]:
train_df = all_df_last.iloc[0:2896,:]
test_df = all_df_last.iloc[2896:,:]
train_df.shape, test_df.shape
train_df

,단지코드,총세대수,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,10분내지하철수,10분내버스정류장수,단지내주차면수,등록차량수,임대건물구분_lbl,지역_lbl,공급유형_lbl,단지코드_lbl
0,C2515,545,33.48,276,17.0,1,9216000,82940,0.0,3.0,624.0,205.0,1,1,1,492
1,C2515,545,39.60,60,17.0,1,12672000,107130,0.0,3.0,624.0,205.0,1,1,1,492
2,C2515,545,39.60,20,17.0,1,12672000,107130,0.0,3.0,624.0,205.0,1,1,1,492
3,C2515,545,46.90,38,17.0,1,18433000,149760,0.0,3.0,624.0,205.0,1,1,1,492
4,C2515,545,46.90,19,17.0,1,18433000,149760,0.0,3.0,624.0,205.0,1,1,1,492
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2891,C2532,239,49.20,19,7.0,1,11346000,116090,0.0,1.0,166.0,146.0,1,5,1,501
2892,C2532,239,51.08,34,7.0,1,14005000,142310,0.0,1.0,166.0,146.0,1,5,1,501
2893,C2532,239,51.73,34,7.0,1,14005000,142310,0.0,1.0,166.0,146.0,1,5,1,501
2894,C2532,239,51.96,114,7.0,1,14005000,142310,0.0,1.0,166.0,146.0,1,5,1,501
2895,C2532,239,54.95,19,7.0,1,14830000,151030,0.0,1.0,166.0,146.0,1,5,1,501

In [60]:
from sklearn.model_selection import train_test_split
sel = [ '총세대수', '전용면적', '전용면적별세대수', '공가수', '자격유형', '10분내버스정류장수',
       '단지내주차면수', '임대건물구분_lbl', '지역_lbl', '공급유형_lbl',
       '단지코드_lbl']
X = train_df[sel]
y = train_df['등록차량수']
test_X = test_df[sel]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [66]:
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

In [62]:
model = LinearRegression()
model.fit(X_train, y_train)
pred = model.predict(X_test)
print("학습(score) :", model.score(X_train, y_train) ) # 결정계수
print("테스트(score) :", model.score(X_test, y_test) ) # 결정계수

학습(score) : 0.7958017751274429
테스트(score) : 0.7988446858976966

In [64]:
mae_val = np.mean( abs( y_test - pred ) )
print( mae_val )
mse_val = np.mean( (y_test - pred) **2 )
print( mse_val )
rmse_val = mse_val ** 0.5
print( rmse_val )

142.35324580904467
40678.21435781545
201.68840908147263

In [67]:
model = RandomForestRegressor(n_jobs=-1)
model.fit(X_train, y_train)
pred = model.predict(X_test)
print("학습(score) :", model.score(X_train, y_train) ) # 결정계수
print("테스트(score) :", model.score(X_test, y_test) ) # 결정계수

학습(score) : 0.9986105338014768
테스트(score) : 0.993431123285369

In [68]:
mae_val = np.mean( abs( y_test - pred ) )
print( mae_val )
mse_val = np.mean( (y_test - pred) **2 )
print( mse_val )
rmse_val = mse_val ** 0.5
print( rmse_val )

16.415281933256637
1328.3774096662853
36.44691221031331

In [70]:
model = RandomForestRegressor(n_jobs=-1)
model.fit(X_train, y_train)
pred = model.predict(test_X)
pred[0:10]

array([ 682.46,  731.43,  685.45,  685.45,  688.75,  687.97,  691.9 ,
        693.08, 1586.22, 1579.46])

In [71]:
test_df['등록차량수'] = pred
test_df['단지별차량수평균'] = test_df.groupby("단지코드")['등록차량수'].transform(np.mean)
test_new = test_df.drop_duplicates(['단지코드'], keep='first').reset_index()
test_new

<ipython-input-71-3cc158f3592c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df['등록차량수'] = pred
<ipython-input-71-3cc158f3592c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df['단지별차량수평균'] = test_df.groupby("단지코드")['등록차량수'].transform(np.mean)

,index,단지코드,총세대수,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,10분내지하철수,10분내버스정류장수,단지내주차면수,등록차량수,임대건물구분_lbl,지역_lbl,공급유형_lbl,단지코드_lbl,단지별차량수평균
0,0,C1072,754,39.79,116,14.0,8,22830000,189840,0.0,2.0,683.0,682.46,1,3,1,32,693.311250
1,8,C1128,1354,39.79,368,9.0,8,22830000,189840,0.0,3.0,1216.0,1586.22,1,3,1,43,1566.935556
2,17,C1456,619,33.40,82,18.0,1,19706000,156200,0.0,16.0,547.0,543.60,1,8,1,143,577.325556
3,26,C1840,593,39.57,253,7.0,1,14418000,108130,0.0,3.0,543.0,589.21,1,4,1,263,599.342500
4,30,C1332,1297,39.99,282,11.0,8,28598000,203050,0.0,2.0,1112.0,1008.72,1,3,1,110,1012.043750
5,38,C1563,1974,39.73,214,15.0,1,30040000,206380,0.0,6.0,1696.0,1253.25,1,3,1,165,1256.118182
6,49,C1794,1349,29.91,245,25.0,1,10273000,92330,0.0,2.0,1098.0,903.13,1,4,1,249,931.440000
7,55,C1640,533,39.51,87,17.0,1,15620000,114140,0.0,1.0,470.0,357.78,1,4,1,192,379.887500
8,59,C1377,470,29.91,62,18.0,1,8394000,71950,0.0,4.0,384.0,379.03,1,1,1,124,345.714000
9,64,C2072,353,33.61,116,6.0,1,8050000,68110,0.0,1.0,280.0,296.54,1,1,1,341,302.192500
10,68,C1472,548,36.62,116,2.0,1,8738000,87380,NaN,1.0,442.0,497.97,1,7,1,148,505.804000
11,73,C1006,1505,26.37,358,27.0,3,5787000,79980,2.0,5.0,428.0,243.16,1,2,3,4,240.449259
12,100,C1083,427,39.85,40,0.0,1,12483000,106090,NaN,6.0,384.0,371.43,1,2,1,34,401.446000
13,105,C1311,383,39.70,22,2.0,1,17286000,265400,0.0,2.0,265.0,353.08,1,8,2,100,353.482500
14,113,C2676,2572,26.37,294,25.0,3,5787000,79980,0.0,2.0,418.0,182.22,1,8,3,553,177.230870
15,159,C2318,420,49.94,276,1.0,1,21801000,234350,2.0,8.0,210.0,312.39,1,8,2,420,309.895000
16,161,C1603,602,39.63,294,0.0,1,13007000,91660,0.0,10.0,491.0,390.44,1,9,1,179,421.140000
17,165,C2523,371,36.65,98,2.0,1,14943000,126030,0.0,13.0,281.0,380.59,1,5,1,496,396.000000
18,168,C2177,1245,26.37,478,2.0,3,3141000,69900,NaN,1.0,187.0,209.80,1,7,3,377,211.084400
19,193,C2411,962,39.43,56,25.0,1,11992000,100720,0.0,2.0,840.0,850.44,1,1,1,455,852.360000
20,198,C2033,1400,26.37,573,12.0,3,4032000,74860,0.0,7.0,308.0,165.46,1,10,3,324,165.856000
21,223,C1604,534,51.49,174,13.0,1,16016000,208870,0.0,2.0,400.0,442.84,1,10,1,180,450.135000
22,225,C2535,558,51.86,462,23.0,1,21883000,202160,0.0,2.0,480.0,500.71,1,10,1,502,515.450000
23,227,C1040,638,36.63,345,24.0,1,14485000,126050,0.0,3.0,548.0,517.60,1,10,1,19,513.850000
24,229,C2417,494,46.90,324,21.0,1,24969000,187260,0.0,4.0,447.0,411.60,1,10,1,459,435.945000
25,231,C1812,1021,26.37,745,22.0,3,3922000,72830,0.0,4.0,185.0,129.40,1,10,3,253,129.808148
26,258,C2253,1161,26.37,745,0.0,3,2249000,44770,0.0,2.0,173.0,106.76,1,5,3,399,106.895484
27,289,C1294,709,51.88,580,28.0,1,15762000,213760,0.0,2.0,571.0,408.56,1,5,1,94,425.433333
28,292,C1772,496,46.90,306,25.0,1,18101000,210970,0.0,3.0,593.0,331.20,1,5,1,241,352.730000
29,295,C2646,584,51.93,330,29.0,1,23536000,192000,0.0,5.0,499.0,396.84,1,5,1,543,400.980000
30,297,C1152,1301,51.77,358,33.0,1,28491000,167230,0.0,2.0,1101.0,1079.92,1,8,1,53,1091.766667
31,300,C2423,207,39.37,104,0.0,1,11858000,102350,0.0,2.0,152.0,161.87,1,9,1,461,163.535000
32,302,C1844,620,36.63,196,0.0,1,14161000,120120,0.0,4.0,498.0,518.72,1,9,1,265,518.696667
33,305,C1318,312,39.51,135,1.0,1,14440000,208840,NaN,11.0,226.0,294.73,1,7,2,103,300.976667
34,308,C1729,627,32.76,180,0.0,3,5009000,93000,0.0,5.0,131.0,84.67,1,5,3,228,85.119200
35,333,C1602,408,36.57,232,0.0,1,9611000,78090,0.0,4.0,319.0,284.02,1,13,1,178,294.141667
36,339,C1239,498,36.55,240,3.0,1,9852000,88900,0.0,8.0,425.0,429.56,1,11,1,79,448.155000
37,343,C1721,663,39.46,155,20.0,1,26435000,180230,0.0,3.0,573.0,496.43,1,3,1,225,505.726667
38,349,C1902,980,36.65,139,21.0,1,22468000,153790,0.0,5.0,841.0,784.24,1,3,1,289,789.055000
39,357,C1855,419,36.55,228,16.0,1,9731000,84100,0.0,3.0,333.0,312.80,1,11,1,271,337.937500
40,361,C2600,540,36.51,270,10.0,1,9611000,96110,0.0,6.0,458.0,461.64,1,4,1,528,481.222000
41,366,C1071,528,46.61,87,16.0,1,16229000,121070,0.0,4.0,403.0,374.78,1,13,1,31,391.334000
42,371,C2295,496,36.66,108,22.0,1,8955000,75240,0.0,1.0,378.0,446.69,1,13,1,413,454.852000
43,376,C1621,593,39.59,171,2.0,1,23720000,197230,0.0,3.0,516.0,528.65,1,3,1,185,540.002857
44,383,C1852,898,39.59,219,6.0,8,23720000,197230,0.0,50.0,785.0,696.29,1,3,1,270,701.325556
45,392,C2555,1442,39.65,343,23.0,1,18174000,101640,0.0,6.0,1225.0,841.80,1,6,1,509,837.838000
46,397,C1297,449,39.72,116,8.0,1,19819000,109230,0.0,3.0,448.0,443.20,1,6,1,95,455.520000
47,402,C2323,603,39.48,112,11.0,1,19973000,111090,0.0,2.0,562.0,541.12,1,6,1,422,547.763750
48,410,C2215,496,36.63,218,8.0,1,13264000,87440,0.0,6.0,350.0,437.53,1,6,1,388,438.992500
49,414,C2112,377,36.55,144,21.0,1,16600000,117670,0.0,4.0,382.0,365.57,1,13,1,355,365.231667
50,420,C1830,891,36.73,314,17.0,1,18581000,157300,1.0,7.0,805.0,687.47,1,3,1,258,692.626667
51,429,C2602,349,29.92,53,5.0,1,8670000,102710,0.0,2.0,270.0,297.75,1,4,1,530,299.425000
52,433,C2608,1138,39.48,133,25.0,1,15111000,126340,0.0,5.0,1141.0,1013.19,1,3,1,533,1035.315000
53,441,C1215,861,36.72,239,3.0,1,15175000,135980,1.0,5.0,660.0,693.47,1,2,1,72,695.991667
54,447,C2369,656,51.86,424,3.0,1,23682000,101160,0.0,3.0,528.0,602.73,1,7,1,439,614.735000
55,449,C1158,262,51.93,90,13.0,1,18726000,110010,0.0,2.0,202.0,292.71,1,12,1,56,294.960000
56,452,C1887,801,36.19,60,21.0,1,19472000,89560,1.0,4.0,611.0,495.65,1,14,1,283,503.916667
57,464,C1189,307,39.72,60,7.0,1,12732000,106090,0.0,3.0,309.0,310.64,1,2,1,66,313.086250
58,472,C1637,525,36.65,127,17.0,1,13007000,86700,0.0,3.0,461.0,361.75,1,3,1,190,376.911667
59,478,C1225,203,51.93,86,8.0,1,18422000,165790,0.0,3.0,159.0,153.74,1,5,1,74,149.356667
60,481,C2374,385,39.56,80,11.0,1,14863000,110230,0.0,3.0,349.0,414.52,1,12,1,442,414.700000
61,487,C2397,557,51.86,446,3.0,1,32376000,272630,0.0,3.0,470.0,518.68,1,3,1,451,550.910000
62,490,C1105,1044,36.79,85,4.0,1,16912000,170360,0.0,6.0,893.0,836.84,1,3,1,40,831.066000
63,500,C1782,503,46.90,146,6.0,1,18726000,112340,0.0,2.0,358.0,424.16,1,5,1,244,434.736000
64,505,C1629,225,46.90,35,2.0,1,22329000,84350,0.0,2.0,159.0,135.89,1,5,1,187,130.543333
65,508,C1708,327,39.51,42,2.0,1,10899000,84220,0.0,7.0,274.0,372.38,1,9,1,221,381.337778
66,517,C2144,828,39.15,106,17.0,1,14356000,114830,0.0,2.0,585.0,680.13,1,8,1,368,680.841429
67,524,C1617,1008,46.48,292,15.0,1,15715000,207380,1.0,4.0,1035.0,1117.89,1,1,1,183,1088.990000
68,528,C1149,531,46.90,90,16.0,1,22173000,151110,0.0,8.0,537.0,546.10,1,3,1,52,551.700000
69,533,C1323,503,39.72,112,19.0,1,16225000,111470,0.0,3.0,507.0,458.24,1,3,1,106,472.705714
70,540,C1064,977,36.72,252,20.0,1,8113000,90370,0.0,7.0,741.0,737.96,1,3,1,28,741.084000
71,545,C1019,321,39.84,132,7.0,1,13276000,107740,0.0,3.0,259.0,320.47,1,9,1,10,323.592500
72,549,C2269,618,39.46,90,4.0,1,18175000,153180,0.0,2.0,545.0,586.07,1,3,1,407,595.284000
73,559,C1416,948,39.59,204,6.0,1,18175000,153180,0.0,1.0,831.0,765.25,1,3,1,134,784.041429
74,566,C1250,981,39.48,177,9.0,1,16649000,163940,0.0,2.0,989.0,841.96,1,3,1,81,847.475000
75,572,C1741,388,51.86,82,0.0,1,25293000,255690,0.0,4.0,392.0,432.89,1,3,1,232,435.840000
76,575,C1016,643,39.64,177,4.0,1,20233000,182630,1.0,4.0,646.0,713.08,1,3,1,8,722.090000
77,579,C2436,708,51.79,119,17.0,5,97541000,50800,0.0,3.0,711.0,557.07,1,10,1,464,581.170000
78,584,C2039,976,39.54,44,7.0,1,17837000,122630,1.0,6.0,884.0,850.83,1,14,1,329,886.573333
79,590,C1253,860,39.54,45,9.0,1,18563000,127200,2.0,6.0,771.0,882.69,1,14,1,82,891.990000
80,596,C2028,1267,51.93,119,26.0,1,24969000,149810,0.0,12.0,1280.0,967.83,1,1,1,322,977.988000
81,601,C1166,359,51.86,191,12.0,1,13929000,121700,0.0,2.0,254.0,299.23,1,11,1,58,301.210000
82,603,C1135,244,36.91,41,6.0,1,17977000,149810,0.0,3.0,211.0,198.63,1,3,1,47,226.136250
83,611,C1216,320,36.91,74,7.0,1,13731000,103580,0.0,1.0,259.0,334.11,1,4,1,73,330.180000
84,614,C1593,332,36.63,230,1.0,7,6171000,89450,0.0,5.0,236.0,341.35,1,11,1,176,257.400000
85,618,C1826,284,39.59,120,20.0,1,9492000,82290,0.0,3.0,213.0,247.73,1,11,1,256,265.716667
86,621,C1827,511,39.51,180,20.0,1,11826000,83370,0.0,1.0,379.0,408.50,1,11,1,257,420.312000
87,626,C1564,354,36.89,88,2.0,1,9537000,74300,0.0,4.0,286.0,286.32,1,13,1,166,288.311429
88,633,C1495,1175,36.63,427,14.0,1,11827000,100270,0.0,4.0,1024.0,1112.47,1,5,1,155,1119.866000
89,638,C2653,879,51.86,348,25.0,1,22876000,232570,0.0,16.0,802.0,859.75,1,3,1,546,872.510000
90,642,C1392,794,36.63,284,17.0,1,11518000,111470,0.0,2.0,645.0,552.44,1,13,1,127,540.611667
91,648,C2128,335,33.13,74,3.0,1,10528000,59440,0.0,4.0,278.0,328.64,1,3,1,358,330.512500
92,652,C1282,745,36.50,188,25.0,1,15920000,131470,0.0,3.0,705.0,666.26,1,11,1,90,679.965000
93,658,C1521,1414,29.41,68,20.0,1,8410000,84100,0.0,4.0,1307.0,1019.69,1,4,1,160,1011.926667
94,667,C2076,1385,33.24,564,25.0,1,10651000,99080,0.0,14.0,1139.0,961.11,1,1,1,343,963.650000
95,673,C1060,659,26.91,118,7.0,1,19945000,135770,0.0,5.0,602.0,533.36,1,3,1,27,559.691429
96,680,C2473,1147,29.73,72,17.0,1,10638000,88650,0.0,1.0,1222.0,996.23,1,6,1,475,993.539167
97,692,C2557,964,46.46,168,31.0,1,28723000,160740,0.0,4.0,818.0,676.95,1,8,1,511,724.094286
98,699,C1835,1060,26.12,210,37.0,1,13221000,143510,0.0,18.0,925.0,915.87,1,3,1,261,940.281429
99,706,C2224,826,51.59,658,26.0,1,27597000,315070,0.0,4.0,746.0,569.74,1,1,1,392,634.875000
100,708,C2222,456,47.00,107,16.0,1,17098000,142660,0.0,3.0,372.0,438.47,1,13,1,391,438.088571
101,715,C2430,687,51.88,151,13.0,1,32313000,484890,0.0,1.0,690.0,752.01,1,2,5,462,778.483333
102,721,C2497,488,59.95,89,37.0,1,31000000,416000,0.0,6.0,624.0,457.48,1,13,5,484,456.647500
103,725,C1494,728,74.95,66,10.0,1,31698000,470010,0.0,5.0,803.0,831.65,1,5,5,154,843.543333
104,728,C1457,736,36.83,440,30.0,1,15113000,233470,0.0,2.0,704.0,527.51,1,10,1,144,533.143333
105,731,C1525,1331,26.47,48,17.0,8,14663000,156780,1.0,6.0,1204.0,1053.75,1,3,1,161,1046.837059
106,748,C1712,737,33.40,90,23.0,1,9216000,133850,0.0,2.0,632.0,508.66,1,13,1,222,519.156667
107,754,C2267,1191,26.12,184,33.0,1,12285000,142800,0.0,15.0,1052.0,1050.51,1,3,1,405,1066.920000
108,764,C1623,296,39.62,50,10.0,1,11235000,93450,0.0,1.0,239.0,288.58,1,13,1,186,305.813333
109,770,C2131,538,51.84,106,5.0,1,25886000,359140,0.0,3.0,451.0,545.22,1,7,5,359,548.370000
110,776,C2691,765,74.89,25,25.0,1,66000000,550000,0.0,19.0,910.0,1344.37,1,3,5,556,1351.543333
111,779,C1147,1124,33.46,64,3.0,1,11401000,172590,0.0,2.0,980.0,762.47,1,1,1,51,754.468571
112,786,C1692,1390,29.13,48,36.0,1,7741000,133330,0.0,2.0,1216.0,1273.93,1,14,1,212,1268.328000
113,791,C1570,1278,36.71,460,36.0,1,7848000,140850,0.0,1.0,1014.0,981.37,1,11,1,170,997.962500
114,795,C1474,190,26.97,70,2.0,8,7224000,129030,0.0,4.0,142.0,117.56,1,1,1,149,117.685000
115,799,C1633,178,26.96,88,22.0,1,10305000,146780,0.0,4.0,168.0,185.44,1,14,1,188,188.010000
116,802,C2113,990,29.75,234,32.0,1,8602000,129030,0.0,2.0,701.0,504.88,1,5,1,356,509.342500
117,810,C2175,595,74.82,118,5.0,1,47000000,470000,0.0,3.0,685.0,845.61,1,1,5,376,857.426667
118,816,C2303,963,74.93,89,16.0,1,48900000,494000,0.0,6.0,1161.0,1341.29,1,3,5,415,1341.171667
119,822,C2547,626,21.99,186,9.0,8,12554000,127000,0.0,8.0,566.0,487.41,1,3,1,506,481.555000
120,828,C2292,906,21.92,336,22.0,8,8738000,131580,0.0,2.0,906.0,860.99,1,16,1,412,872.768000
121,833,C1496,565,75.90,118,11.0,1,28000000,440000,0.0,3.0,582.0,641.59,1,11,5,156,644.193333
122,836,C1289,482,26.91,124,15.0,8,9494000,109220,0.0,2.0,423.0,423.99,1,5,1,93,432.920000
123,841,C1849,1054,26.92,344,6.0,8,7800000,131000,0.0,3.0,824.0,741.39,1,5,1,268,744.466000
124,846,C1003,480,16.69,128,29.0,10,12000000,61000,0.0,3.0,339.0,318.18,1,1,9,1,324.765000
125,854,C2268,900,17.23,80,45.0,11,33446000,17420,0.0,2.0,633.0,437.53,1,1,9,406,435.688182
126,865,C2551,674,21.99,160,18.0,8,8768000,123360,0.0,2.0,674.0,514.42,1,16,1,508,509.268333
127,871,C2688,150,26.59,44,1.0,8,4831000,86350,0.0,3.0,107.0,67.06,1,12,1,555,66.173333
128,877,C1030,75,16.39,14,12.0,10,34240000,142660,1.0,2.0,29.0,46.41,1,3,9,15,46.396667
129,883,C2451,395,59.18,23,2.0,1,50000000,450000,0.0,3.0,433.0,531.48,1,14,5,469,535.730000
130,887,C1749,848,20.59,200,34.0,10,21999000,100820,0.0,8.0,675.0,480.88,1,3,9,235,488.398889
131,896,C1349,465,16.85,129,20.0,13,12780000,74000,0.0,3.0,322.0,270.85,1,6,9,116,272.055714
132,903,C2043,469,16.95,186,23.0,10,18300000,82500,0.0,4.0,330.0,294.40,1,1,9,332,297.437143
133,910,C1229,453,19.32,262,23.0,10,16228000,64910,0.0,2.0,317.0,294.92,1,16,9,76,293.040000
134,918,C2363,864,16.78,120,36.0,12,12920000,75000,0.0,6.0,603.0,465.66,1,8,9,437,453.875000
135,924,C1414,873,16.80,338,29.0,10,16520000,77000,0.0,8.0,610.0,349.71,1,3,9,133,389.864286
136,931,C2174,954,16.97,416,41.0,14,14700000,80000,0.0,3.0,667.0,478.94,1,10,9,375,477.196000
137,936,C2091,150,29.39,66,4.0,1,5910000,122000,0.0,1.0,120.0,149.72,1,11,1,347,143.120000
138,941,C1841,100,16.80,40,14.0,10,16768000,86630,0.0,4.0,53.0,93.75,1,6,9,264,93.530000
139,946,C2404,214,16.87,2,15.0,10,12480000,78000,0.0,5.0,117.0,138.99,1,12,9,453,138.840909
140,968,C1683,328,21.54,40,14.0,10,14498000,62940,0.0,11.0,250.0,241.58,1,3,9,208,243.410000
141,976,C1038,554,16.94,136,34.0,11,35897000,18690,0.0,1.0,387.0,345.22,1,11,9,17,355.800000
142,982,C2456,349,26.44,24,17.0,8,6992000,117000,0.0,4.0,270.0,209.88,1,9,1,471,214.332500
143,986,C1266,596,26.94,164,35.0,8,8084000,149910,0.0,1.0,593.0,510.36,1,11,1,85,524.140000
144,991,C2152,120,24.83,66,9.0,3,-,-,0.0,1.0,40.0,29.53,1,5,3,369,29.765000
145,993,C1267,675,24.87,28,38.0,8,6882000,104370,0.0,1.0,467.0,422.39,1,1,1,86,432.301818
146,1004,C2189,382,29.19,96,45.0,8,6872000,106400,0.0,2.0,300.0,298.28,1,4,1,381,297.135000

In [72]:
add_dat = {'code':['C2675', 'C2335', 'C1327'],
           'num':['0', '0', '0']}
add_df = pd.DataFrame(add_dat)
add_df

    code num
0  C2675   0
1  C2335   0
2  C1327   0

In [73]:
sub_df = test_new[ ['단지코드', '단지별차량수평균']]
sub_df.columns = ['code', 'num']
sub_df = pd.concat([sub_df, add_df]).reset_index()
sub_df = sub_df.drop(['index'], axis=1)
sub_df

      code      num
0    C1072  693.311
1    C1128  1566.94
2    C1456  577.326
3    C1840  599.342
4    C1332  1012.04
5    C1563  1256.12
6    C1794   931.44
7    C1640  379.887
8    C1377  345.714
9    C2072  302.192
10   C1472  505.804
11   C1006  240.449
12   C1083  401.446
13   C1311  353.482
14   C2676  177.231
15   C2318  309.895
16   C1603   421.14
17   C2523      396
18   C2177  211.084
19   C2411   852.36
20   C2033  165.856
21   C1604  450.135
22   C2535   515.45
23   C1040   513.85
24   C2417  435.945
25   C1812  129.808
26   C2253  106.895
27   C1294  425.433
28   C1772   352.73
29   C2646   400.98
30   C1152  1091.77
31   C2423  163.535
32   C1844  518.697
33   C1318  300.977
34   C1729  85.1192
35   C1602  294.142
36   C1239  448.155
37   C1721  505.727
38   C1902  789.055
39   C1855  337.938
40   C2600  481.222
41   C1071  391.334
42   C2295  454.852
43   C1621  540.003
44   C1852  701.326
45   C2555  837.838
46   C1297   455.52
47   C2323  547.764
48   C2215  438.993
49   C2112  365.232
50   C1830  692.627
51   C2602  299.425
52   C2608  1035.32
53   C1215  695.992
54   C2369  614.735
55   C1158   294.96
56   C1887  503.917
57   C1189  313.086
58   C1637  376.912
59   C1225  149.357
60   C2374    414.7
61   C2397   550.91
62   C1105  831.066
63   C1782  434.736
64   C1629  130.543
65   C1708  381.338
66   C2144  680.841
67   C1617  1088.99
68   C1149    551.7
69   C1323  472.706
70   C1064  741.084
71   C1019  323.592
72   C2269  595.284
73   C1416  784.041
74   C1250  847.475
75   C1741   435.84
76   C1016   722.09
77   C2436   581.17
78   C2039  886.573
79   C1253   891.99
80   C2028  977.988
81   C1166   301.21
82   C1135  226.136
83   C1216   330.18
84   C1593    257.4
85   C1826  265.717
86   C1827  420.312
87   C1564  288.311
88   C1495  1119.87
89   C2653   872.51
90   C1392  540.612
91   C2128  330.512
92   C1282  679.965
93   C1521  1011.93
94   C2076   963.65
95   C1060  559.691
96   C2473  993.539
97   C2557  724.094
98   C1835  940.281
99   C2224  634.875
100  C2222  438.089
101  C2430  778.483
102  C2497  456.647
103  C1494  843.543
104  C1457  533.143
105  C1525  1046.84
106  C1712  519.157
107  C2267  1066.92
108  C1623  305.813
109  C2131   548.37
110  C2691  1351.54
111  C1147  754.469
112  C1692  1268.33
113  C1570  997.962
114  C1474  117.685
115  C1633   188.01
116  C2113  509.342
117  C2175  857.427
118  C2303  1341.17
119  C2547  481.555
120  C2292  872.768
121  C1496  644.193
122  C1289   432.92
123  C1849  744.466
124  C1003  324.765
125  C2268  435.688
126  C2551  509.268
127  C2688  66.1733
128  C1030  46.3967
129  C2451   535.73
130  C1749  488.399
131  C1349  272.056
132  C2043  297.437
133  C1229   293.04
134  C2363  453.875
135  C1414  389.864
136  C2174  477.196
137  C2091   143.12
138  C1841    93.53
139  C2404  138.841
140  C1683   243.41
141  C1038    355.8
142  C2456  214.332
143  C1266   524.14
144  C2152   29.765
145  C1267  432.302
146  C2189  297.135
147  C2675        0
148  C2335        0
149  C1327        0

In [74]:
sub_df = test_new[ ['단지코드', '단지별차량수평균']]
sub_df.columns = ['code', 'num']
sub_df = pd.concat([sub_df, add_df]).reset_index()
sub_df = sub_df.drop(['index'], axis=1)
sub_df

      code      num
0    C1072  693.311
1    C1128  1566.94
2    C1456  577.326
3    C1840  599.342
4    C1332  1012.04
5    C1563  1256.12
6    C1794   931.44
7    C1640  379.887
8    C1377  345.714
9    C2072  302.192
10   C1472  505.804
11   C1006  240.449
12   C1083  401.446
13   C1311  353.482
14   C2676  177.231
15   C2318  309.895
16   C1603   421.14
17   C2523      396
18   C2177  211.084
19   C2411   852.36
20   C2033  165.856
21   C1604  450.135
22   C2535   515.45
23   C1040   513.85
24   C2417  435.945
25   C1812  129.808
26   C2253  106.895
27   C1294  425.433
28   C1772   352.73
29   C2646   400.98
30   C1152  1091.77
31   C2423  163.535
32   C1844  518.697
33   C1318  300.977
34   C1729  85.1192
35   C1602  294.142
36   C1239  448.155
37   C1721  505.727
38   C1902  789.055
39   C1855  337.938
40   C2600  481.222
41   C1071  391.334
42   C2295  454.852
43   C1621  540.003
44   C1852  701.326
45   C2555  837.838
46   C1297   455.52
47   C2323  547.764
48   C2215  438.993
49   C2112  365.232
50   C1830  692.627
51   C2602  299.425
52   C2608  1035.32
53   C1215  695.992
54   C2369  614.735
55   C1158   294.96
56   C1887  503.917
57   C1189  313.086
58   C1637  376.912
59   C1225  149.357
60   C2374    414.7
61   C2397   550.91
62   C1105  831.066
63   C1782  434.736
64   C1629  130.543
65   C1708  381.338
66   C2144  680.841
67   C1617  1088.99
68   C1149    551.7
69   C1323  472.706
70   C1064  741.084
71   C1019  323.592
72   C2269  595.284
73   C1416  784.041
74   C1250  847.475
75   C1741   435.84
76   C1016   722.09
77   C2436   581.17
78   C2039  886.573
79   C1253   891.99
80   C2028  977.988
81   C1166   301.21
82   C1135  226.136
83   C1216   330.18
84   C1593    257.4
85   C1826  265.717
86   C1827  420.312
87   C1564  288.311
88   C1495  1119.87
89   C2653   872.51
90   C1392  540.612
91   C2128  330.512
92   C1282  679.965
93   C1521  1011.93
94   C2076   963.65
95   C1060  559.691
96   C2473  993.539
97   C2557  724.094
98   C1835  940.281
99   C2224  634.875
100  C2222  438.089
101  C2430  778.483
102  C2497  456.647
103  C1494  843.543
104  C1457  533.143
105  C1525  1046.84
106  C1712  519.157
107  C2267  1066.92
108  C1623  305.813
109  C2131   548.37
110  C2691  1351.54
111  C1147  754.469
112  C1692  1268.33
113  C1570  997.962
114  C1474  117.685
115  C1633   188.01
116  C2113  509.342
117  C2175  857.427
118  C2303  1341.17
119  C2547  481.555
120  C2292  872.768
121  C1496  644.193
122  C1289   432.92
123  C1849  744.466
124  C1003  324.765
125  C2268  435.688
126  C2551  509.268
127  C2688  66.1733
128  C1030  46.3967
129  C2451   535.73
130  C1749  488.399
131  C1349  272.056
132  C2043  297.437
133  C1229   293.04
134  C2363  453.875
135  C1414  389.864
136  C2174  477.196
137  C2091   143.12
138  C1841    93.53
139  C2404  138.841
140  C1683   243.41
141  C1038    355.8
142  C2456  214.332
143  C1266   524.14
144  C2152   29.765
145  C1267  432.302
146  C2189  297.135
147  C2675        0
148  C2335        0
149  C1327        0

In [75]:
sub_df.to_csv('third_rf_0719.csv', index=False)
sub_df.head()

    code      num
0  C1072  693.311
1  C1128  1566.94
2  C1456  577.326
3  C1840  599.342
4  C1332  1012.04